# ?????
server.port=50000

# ???? API ??
aliyun.dashscope.api-key=sk-ab5cb8e4c09c4f30b4a0d0dc2fc9f154
aliyun.dashscope.model=qwen-turbo

# MySQL ?????
spring.datasource.url=jdbc:mysql://localhost:3306/ai_interview?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=791124
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true